/* tslint:disable */
/* eslint-disable */
/**
 * Live Course Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchRouteRequest
 */
export interface PatchRouteRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchRouteRequest
     */
    estimatedAverageSpeed?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchRouteRequest
     */
    estimatedStartTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof PatchRouteRequest
     */
    pauseInMinutes?: number;
}

/**
 * Check if a given object implements the PatchRouteRequest interface.
 */
export function instanceOfPatchRouteRequest(value: object): value is PatchRouteRequest {
    return true;
}

export function PatchRouteRequestFromJSON(json: any): PatchRouteRequest {
    return PatchRouteRequestFromJSONTyped(json, false);
}

export function PatchRouteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchRouteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'estimatedAverageSpeed': json['estimatedAverageSpeed'] == null ? undefined : json['estimatedAverageSpeed'],
        'estimatedStartTime': json['estimatedStartTime'] == null ? undefined : (new Date(json['estimatedStartTime'])),
        'pauseInMinutes': json['pauseInMinutes'] == null ? undefined : json['pauseInMinutes'],
    };
}

export function PatchRouteRequestToJSON(json: any): PatchRouteRequest {
    return PatchRouteRequestToJSONTyped(json, false);
}

export function PatchRouteRequestToJSONTyped(value?: PatchRouteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'estimatedAverageSpeed': value['estimatedAverageSpeed'],
        'estimatedStartTime': value['estimatedStartTime'] == null ? undefined : ((value['estimatedStartTime']).toISOString()),
        'pauseInMinutes': value['pauseInMinutes'],
    };
}

