/* tslint:disable */
/* eslint-disable */
/**
 * Live Course Control API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoutePointResponse
 */
export interface RoutePointResponse {
    /**
     * 
     * @type {number}
     * @memberof RoutePointResponse
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof RoutePointResponse
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof RoutePointResponse
     */
    altitude: number;
}

/**
 * Check if a given object implements the RoutePointResponse interface.
 */
export function instanceOfRoutePointResponse(value: object): value is RoutePointResponse {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('altitude' in value) || value['altitude'] === undefined) return false;
    return true;
}

export function RoutePointResponseFromJSON(json: any): RoutePointResponse {
    return RoutePointResponseFromJSONTyped(json, false);
}

export function RoutePointResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoutePointResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'altitude': json['altitude'],
    };
}

export function RoutePointResponseToJSON(json: any): RoutePointResponse {
    return RoutePointResponseToJSONTyped(json, false);
}

export function RoutePointResponseToJSONTyped(value?: RoutePointResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'altitude': value['altitude'],
    };
}

