/* tslint:disable */
/* eslint-disable */
/**
 * Head Of TP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoleType } from './RoleType';
import {
    RoleTypeFromJSON,
    RoleTypeFromJSONTyped,
    RoleTypeToJSON,
    RoleTypeToJSONTyped,
} from './RoleType';
import type { VehicleType } from './VehicleType';
import {
    VehicleTypeFromJSON,
    VehicleTypeFromJSONTyped,
    VehicleTypeToJSON,
    VehicleTypeToJSONTyped,
} from './VehicleType';

/**
 * 
 * @export
 * @interface CreateParticipantRequest
 */
export interface CreateParticipantRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateParticipantRequest
     */
    name: string;
    /**
     * 
     * @type {VehicleType}
     * @memberof CreateParticipantRequest
     */
    vehicle: VehicleType;
    /**
     * 
     * @type {RoleType}
     * @memberof CreateParticipantRequest
     */
    role: RoleType;
    /**
     * 
     * @type {string}
     * @memberof CreateParticipantRequest
     */
    deviceId: string;
}



/**
 * Check if a given object implements the CreateParticipantRequest interface.
 */
export function instanceOfCreateParticipantRequest(value: object): value is CreateParticipantRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('vehicle' in value) || value['vehicle'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    return true;
}

export function CreateParticipantRequestFromJSON(json: any): CreateParticipantRequest {
    return CreateParticipantRequestFromJSONTyped(json, false);
}

export function CreateParticipantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateParticipantRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'vehicle': VehicleTypeFromJSON(json['vehicle']),
        'role': RoleTypeFromJSON(json['role']),
        'deviceId': json['deviceId'],
    };
}

export function CreateParticipantRequestToJSON(json: any): CreateParticipantRequest {
    return CreateParticipantRequestToJSONTyped(json, false);
}

export function CreateParticipantRequestToJSONTyped(value?: CreateParticipantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'vehicle': VehicleTypeToJSON(value['vehicle']),
        'role': RoleTypeToJSON(value['role']),
        'deviceId': value['deviceId'],
    };
}

