/* tslint:disable */
/* eslint-disable */
/**
 * Head Of TP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceLocationBattery
 */
export interface DeviceLocationBattery {
    /**
     * 
     * @type {number}
     * @memberof DeviceLocationBattery
     */
    level: number;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceLocationBattery
     */
    isCharging: boolean;
}

/**
 * Check if a given object implements the DeviceLocationBattery interface.
 */
export function instanceOfDeviceLocationBattery(value: object): value is DeviceLocationBattery {
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('isCharging' in value) || value['isCharging'] === undefined) return false;
    return true;
}

export function DeviceLocationBatteryFromJSON(json: any): DeviceLocationBattery {
    return DeviceLocationBatteryFromJSONTyped(json, false);
}

export function DeviceLocationBatteryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceLocationBattery {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'],
        'isCharging': json['is_charging'],
    };
}

export function DeviceLocationBatteryToJSON(json: any): DeviceLocationBattery {
    return DeviceLocationBatteryToJSONTyped(json, false);
}

export function DeviceLocationBatteryToJSONTyped(value?: DeviceLocationBattery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': value['level'],
        'is_charging': value['isCharging'],
    };
}

