/* tslint:disable */
/* eslint-disable */
/**
 * Head Of TP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceResponse
 */
export interface DeviceResponse {
    /**
     * 
     * @type {string}
     * @memberof DeviceResponse
     */
    id: string;
}

/**
 * Check if a given object implements the DeviceResponse interface.
 */
export function instanceOfDeviceResponse(value: object): value is DeviceResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DeviceResponseFromJSON(json: any): DeviceResponse {
    return DeviceResponseFromJSONTyped(json, false);
}

export function DeviceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeviceResponseToJSON(json: any): DeviceResponse {
    return DeviceResponseToJSONTyped(json, false);
}

export function DeviceResponseToJSONTyped(value?: DeviceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

