name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
  id-token: write

env:
  AWS_ROLE: 'arn:aws:iam::896918338968:role/GitHubActionsHeadOfTpFrontend'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22

      - name: Build Project
        run: |
          rm -rf dist
          npm install
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Terraform Format Check
        id: fmt-check
        run: terraform fmt -check
        working-directory: infra

      - name: Install Semantic Release and plugins
        run: |
          npm install semantic-release @semantic-release/exec @semantic-release/changelog @semantic-release/github

      - name: Create Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "docs(CHANGELOG): Update CHANGELOG.md"
          git push origin main

      - name: Update develop branch
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch origin
          git checkout develop
          git merge --ff-only origin/main
          git push origin develop

      - name: Terraform init
        if: github.ref == 'refs/heads/develop'
        id: tf-init
        run: terraform init
        working-directory: infra/prod

      - name: Terraform plan
        if: github.ref == 'refs/heads/develop'
        id: tf-plan
        run: terraform plan
        working-directory: infra/prod

      - name: Terraform apply
        if: github.ref == 'refs/heads/develop'
        id: tf-apply
        run: terraform apply -auto-approve
        working-directory: infra/prod
